# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0876f682a35e3400d814415d93310b339f487ef21aceb233090e4fc2f6d5768772107ace67d4702777fcc8d4431abb0d097544e16115e85174989eba701f476

test:
  secret_key_base: 75d42f1bd9b62e110012a5807da470113b7b809b7b335976b8c3385fefffd6f28b4066049d15feb119fcfd65850fba7e1d6a23260363a16a2f2e348d2adffe60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
